### ISSUE TITLE
您好，请教下扫码结果为null呢

### ISSUE THREAD

**Issue by beclass** [isboyjc/wechaty-Robot#2]
node index.js 启动后，微信扫码结果
![image](https://user-images.githubusercontent.com/12541388/79448307-c66d3080-8013-11ea-9c85-e94469c0f741.png)

**Comment by isboyjc** [comment]
onScan回调中输出qrcode码，复制并使用链接转二维码工具转成二维码进行扫描

**Comment by isboyjc** [comment]
可以加下小助手微信，加群交流下
